### ISSUE TITLE
При переводе между своими картами баланс уходит в минус

### ISSUE THREAD

**Issue by Masha1986** [Masha1986/Page-Object-s#1]
Шаги для воспроизведения

Запустить в IDEA SUT app-ibank-build-for-testers;
Перейти по ссылке http://localhost:9999/;
Залогиниться: Логин -"vasya" , Пароль - "qwerty123";
Ввести в поле "Код из смс или push" значение : "12345";
Пополнить баланс второй карты 5559 0000 0000 0002 (изначально на данной карте 10 000 рублей)
 с карты 5559 0000 0000 0001 (изначально на данной карте 10 000 рублей) на сумму 2000 рублей.

                   **Ожидаемый результат**
На карте 5559 0000 0000 0002 отразится сумма 12 000 рублей,
на карте 5559 0000 0000 0001 отразится сумма 8000 рублей.

                  **Фактический результат**
Баланс карты 5559 0000 0000 0001 ушел в минус.
Сумма пополнения карты 5559 0000 0000 0002 рассчитана неверно.
![10000](https://user-images.githubusercontent.com/93191535/158549109-78b49bd0-7643-4f16-8142-b9271a1700f0.png)

Программное окружение
Windows 10 Pro 
Java 11.0.12
IntelliJ IDEA СЕ version: 2021.3

**Comment by andrew-pahomov** [comment]
Добрый день. Не согласен репортом. При выполнении описанных Вами шагов отрицательного баланса не наблюдаю ни на одной карте. В шагах описана ситуация с валидным переводом, не вижу в них никаких проблем.

**Comment by andrew-pahomov** [comment]
Если Вы решите увеличить сумму перевода(больше чем на остатке карты списания), то получится негативный сценарий. Это вполне возможно, только ожидать после выполнения операции перевода изменения балансов обеих карт неправильно. Ошибочная операция должна быть заблокирована.
